def sumar (n1,n2):
    return (n1+n2)
def restar (n1,n2):
    return (n1-n2)
def mulriplicar (n1,n2):
    return (n1*n2)
def dividir (n1,n2):
    return (n1/n2)

 n1 = int (input("ingresa el numero 1:"))
 n2 = int (input("ingresa el numero 2:"))

print("La suma es: ", sumar(n1,n2))
print("La resta es: ", restar(n1,n2))
print("La multiplicación es: ", multiplicar(n1,n2))
print("La dividir es: ", dividir(n1,n2))



